// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk70bSFjUr6PqD0kntkTYs88E2T20nNEY',
    appId: '1:909650163199:web:56c6091fcaf9bb23dfa3ca',
    messagingSenderId: '909650163199',
    projectId: 'mynotes-1a120',
    authDomain: 'mynotes-1a120.firebaseapp.com',
    storageBucket: 'mynotes-1a120.appspot.com',
    measurementId: 'G-VDXGZ9TZYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybPKH851HoJarUTdIMuaNKn7uFOYMcsE',
    appId: '1:909650163199:android:78678638c7e9deb0dfa3ca',
    messagingSenderId: '909650163199',
    projectId: 'mynotes-1a120',
    storageBucket: 'mynotes-1a120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAxSjLbo3lvDPFPi1ENhqCW8mNEGF2eA',
    appId: '1:909650163199:ios:11987b55570ac426dfa3ca',
    messagingSenderId: '909650163199',
    projectId: 'mynotes-1a120',
    storageBucket: 'mynotes-1a120.appspot.com',
    iosClientId: '909650163199-jflou2drumlcgoecbt9veuk4a98qvuuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAxSjLbo3lvDPFPi1ENhqCW8mNEGF2eA',
    appId: '1:909650163199:ios:1222f722d0dd26a2dfa3ca',
    messagingSenderId: '909650163199',
    projectId: 'mynotes-1a120',
    storageBucket: 'mynotes-1a120.appspot.com',
    iosClientId: '909650163199-qn9fum9t4q4nkd754edaa6ani43iumjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
